package main

import (
	"encoding/json"
	"fmt"
	"os"
	"strconv"
	"strings"
)

// niktoConfig mirrors manifest.yaml configSchema. Keys are camelCase to match
// the OASM_CONFIG JSON shape the Worker ships per job.
type niktoConfig struct {
	Tuning         string   `json:"tuning"`
	Ports          string   `json:"ports"`
	SSL            bool     `json:"ssl"`
	Root           string   `json:"root"`
	Vhost          string   `json:"vhost"`
	UserAgent      string   `json:"userAgent"`
	MaxTime        string   `json:"maxTime"`
	Timeout        int      `json:"timeout"`
	Pause          int      `json:"pause"`
	Headers        []string `json:"headers"`
	NoLookup       bool     `json:"noLookup"`
	NoCookies      bool     `json:"noCookies"`
	FollowRedirect bool     `json:"followRedirects"`
	Evasion        string   `json:"evasion"`
	Plugins        string   `json:"plugins"`
	Proxy          string   `json:"proxy"`
	Username       string   `json:"username"`
	Password       string   `json:"password"`
	No404          bool     `json:"no404"`
}

// loadNiktoConfig reads the per-job config profile from OASM_CONFIG. An unset
// or empty value yields a zero config (all nikto defaults), not an error.
func loadNiktoConfig() (*niktoConfig, error) {
	raw := strings.TrimSpace(os.Getenv("OASM_CONFIG"))
	if raw == "" {
		return &niktoConfig{}, nil
	}
	var cfg niktoConfig
	if err := json.Unmarshal([]byte(raw), &cfg); err != nil {
		return nil, fmt.Errorf("invalid OASM_CONFIG: %w", err)
	}
	return &cfg, nil
}

// niktoConfigFile overrides every setting the adapter drives on the command
// line. It exists for one reason: nikto's own defaults ask two interactive
// questions — UPDATES=yes prompts to submit unidentified server banners, and
// PROMPTS=yes leaves read_data() live — and a non-interactive container would
// sit at that prompt until the job timeout. Neither has a CLI flag, so the
// answers must arrive through a config file (-config). UPDATES=no is also the
// correct default for a scanner that must not phone home.
//
// ponytail: -config replaces the shipped nikto.conf.default wholesale (nikto
// loads the first readable file and stops), so this file must stay complete
// for the options the adapter touches. -Option K=V overrides it per scan.
const niktoConfigFile = `# Generated by the OASM nikto connector — do not edit.
# nikto.conf is not merged with nikto.conf.default: the first readable file wins.
# -Option KEY=VALUE on the command line overrides any entry below.
NIKTODTD=templates/nikto.dtd
DEFAULTHTTPVER=1.1
UPDATES=no
PROMPTS=no
CIRT=cirt.net
CHECKMETHODS=GET
@@EXTRAS=dictionary;siebel
@@DEFAULT=@@ALL;-@@EXTRAS;tests(report:500)
LW_SSL_ENGINE=auto
FAILURES=20
`

// normalizeTarget turns a bare host or partial URL into the URL nikto expects
// for -h. Unlike the crawler connectors the port must survive: `example.com:8443`
// is a different scan target from `example.com`.
func normalizeTarget(raw string) string {
	s := strings.TrimSpace(raw)
	if s == "" {
		return ""
	}
	// A bare host:port with no scheme would otherwise be read as scheme "example.com".
	if !strings.HasPrefix(s, "http://") && !strings.HasPrefix(s, "https://") {
		s = "https://" + s
	}
	return s
}

// hostArg resolves the value for -h. nikto refuses `-port` together with a full
// URI (set_targets: "-port option cannot be used with a full URI", exit 1), so
// when the caller selects ports the target is reduced back to a bare host and
// the scheme is expressed through -ssl instead. Without ports the URL is passed
// through untouched.
func hostArg(target string, cfg *niktoConfig) string {
	if cfg.Ports == "" {
		return target
	}
	rest := strings.TrimPrefix(strings.TrimPrefix(target, "https://"), "http://")
	// Drop any port the URL carried: -port is the authority on ports here.
	if i := strings.IndexAny(rest, "/?#"); i >= 0 {
		rest = rest[:i]
	}
	if i := strings.LastIndex(rest, ":"); i >= 0 && !strings.Contains(rest[i:], "]") {
		rest = rest[:i]
	}
	return rest
}

// usesHTTPS reports whether an explicit -ssl flag is required. nikto infers TLS
// from an https:// URL by itself, so the flag is only needed when the URL's
// scheme was stripped — i.e. when -port forced a bare-host -h argument — or
// when the caller asked for it directly.
func usesHTTPS(target string, cfg *niktoConfig) bool {
	if cfg.SSL {
		return true
	}
	return cfg.Ports != "" && strings.HasPrefix(target, "https://")
}

// buildNiktoArgs assembles the nikto CLI arg vector. Zero values are omitted so
// only explicitly configured options are passed; -config and -nointeractive are
// always present (see niktoConfigFile).
func buildNiktoArgs(target string, cfg *niktoConfig, configPath string) []string {
	// -nointeractive stops nikto from polling stdin for its runtime toggles.
	// No -Display: every informative line then lands on stdout as "+ msg".
	args := []string{"-h", hostArg(target, cfg), "-config", configPath, "-nointeractive"}

	if cfg.Tuning != "" {
		args = append(args, "-Tuning", cfg.Tuning)
	}
	if cfg.Ports != "" {
		args = append(args, "-port", cfg.Ports)
	}
	if usesHTTPS(target, cfg) {
		args = append(args, "-ssl")
	}
	if cfg.Root != "" {
		args = append(args, "-root", cfg.Root)
	}
	if cfg.Vhost != "" {
		args = append(args, "-vhost", cfg.Vhost)
	}
	if cfg.UserAgent != "" {
		args = append(args, "-useragent", cfg.UserAgent)
	}
	if cfg.MaxTime != "" {
		args = append(args, "-maxtime", cfg.MaxTime)
	}
	if cfg.Timeout > 0 {
		args = append(args, "-timeout", strconv.Itoa(cfg.Timeout))
	}

	if cfg.Pause > 0 {
		args = append(args, "-Pause", strconv.FormatFloat(float64(cfg.Pause), 'f', -1, 64))
	}
	for _, h := range cfg.Headers {
		if strings.TrimSpace(h) != "" {
			args = append(args, "-Add-header", h)
		}
	}
	if cfg.NoLookup {
		args = append(args, "-nolookup")
	}
	if cfg.NoCookies {
		args = append(args, "-nocookies")
	}
	if cfg.FollowRedirect {
		args = append(args, "-followredirects")
	}
	if cfg.No404 {
		args = append(args, "-no404")
	}
	if cfg.Evasion != "" {
		args = append(args, "-evasion", cfg.Evasion)
	}
	if cfg.Plugins != "" {
		args = append(args, "-Plugins", cfg.Plugins)
	}
	if cfg.Proxy != "" {
		args = append(args, "-useproxy", cfg.Proxy)
	}
	if cfg.Username != "" {
		args = append(args, "-id", cfg.Username+":"+cfg.Password)
	}

	return args
}
